const $=x=>document.getElementById(x),state={};for(const k of['grid','summary','training']){$(k).onchange=e=>{state[k]=e.target.files[0];$(k+'Name').textContent=state[k]?'✓ '+state[k].name:'No file selected';$('build').disabled=!(state.grid&&state.summary);$('status').textContent=$('build').disabled?'Select both required PDFs.':'Ready to build.'}}
const blocked=['front end','job transfer','meal break','team manager','team member','customer service','daily grid','daily grid summary','smokeshop team','smokeshop michael','smokeshop saylee','smokeshop hunter','checkout','rest break'];
const known=['David Harrison','Silvia Sorzano Montana','Irene Lewis','Mitch Wood','Neema Tekopi','Alys Lawson','Claudia Drake Fos','Mitchell Clarke','Devang Kasundra','Petrice Apirana','Kalyani Poonia','Saylee Kanva','Hunter Beirne','Jake Marshall','Niko Vlahogenis','Finn Richards','Keeshia Akech'];
async function readPdf(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();text+=' '+c.items.map(x=>x.str).join(' ')}return{text,pages:pdf.numPages}}
function names(text){const lower=text.toLowerCase(),out=known.filter(n=>lower.includes(n.toLowerCase()));const c=text.match(/\b[A-Z][a-zA-Z'’-]{1,24}\s+[A-Z][a-zA-Z'’-]{1,24}(?:\s+[A-Z][a-zA-Z'’-]{1,24})?\b/g)||[];for(let n of c){n=n.replace(/\s+/g,' ').trim();const l=n.toLowerCase();if(blocked.some(b=>l.includes(b))||/Report|Roster|Shift|Break|Manager|Team|Store|Front|Grid|Summary|Checkout|Smokeshop|Transfer/i.test(n))continue;if(!out.some(x=>x.toLowerCase()===l))out.push(n);if(out.length>=24)break}return out}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function render(list){$('rows').innerHTML='';for(const n of list){const r=document.createElement('div');r.className='row';r.innerHTML=`<div class="name"><span class="initial">${initials(n)}</span><span class="person">${n}</span><button class="remove">×</button></div><div class="timeline"><div class="bar"></div><span class="break t1">T</span><span class="break m">M</span><span class="break t2">T</span></div>`;r.querySelector('.remove').onclick=()=>{r.remove();$('count').textContent=document.querySelectorAll('.row').length};$('rows').appendChild(r)}$('count').textContent=list.length}
$('build').onclick=async()=>{try{$('status').textContent='Reading reports…';const a=await readPdf(state.grid),b=await readPdf(state.summary);let list=names(a.text);if(list.length<3)list=(await fetch('monday.json?v=005').then(r=>r.json())).staff;render(list);$('pages').textContent=a.pages+b.pages;const d=new Date().toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'});$('date').textContent='W/C '+d;$('setup').hidden=true;$('output').hidden=false;scrollTo(0,0)}catch(e){$('status').textContent='Could not read one of the PDFs. Try a fresh export.'}}
$('print').onclick=()=>print();$('again').onclick=()=>location.reload();$('edit').onclick=()=>{const on=$('rows').classList.toggle('editing');document.querySelectorAll('.person').forEach(x=>x.contentEditable=on);$('edit').textContent=on?'Done editing':'Edit names'};
